Repository jfrog/jfrog-cli-security, pull requests merged in 2024-05, with the labels that each got.

#62 Update xr commands help layout
  cli/cli.go
Labels: improvement

#61 Add classifier to maven graph
  buildscripts/download-jars.sh
  commands/audit/sca/common.go
  commands/audit/sca/common_test.go
  commands/audit/sca/java/deptreemanager.go
  commands/audit/sca/java/gradle.go
  commands/audit/sca/java/mvn.go
  commands/audit/sca/java/mvn_test.go
  commands/audit/sca/java/resources/maven-dep-tree.jar
  commands/audit/sca/npm/npm.go
  commands/audit/sca/nuget/nuget.go
  commands/audit/sca/pnpm/pnpm.go
  commands/audit/sca/yarn/yarn.go
  commands/audit/scarunner.go
  commands/curation/curationaudit.go
  go.mod
  go.sum
  tests/testdata/projects/package-managers/maven/maven-example-with-many-types/pom.xml
  utils/xrayutils.go
Labels: bug

#63 Add summary format
  commands/audit/scarunner.go
  commands/audit/scarunner_test.go
  commands/scan/buildscan.go
  commands/scan/scan.go
  formats/summary.go
  formats/summary_test.go
  go.mod
  go.sum
  tests/testdata/other/jobSummary/multi_command_job.md
  tests/testdata/other/jobSummary/single_issue.md
  tests/testdata/other/jobSummary/single_no_issue.md
  utils/analyticsmetrics_test.go
  utils/analyzermanager.go
  utils/results.go
  utils/results_test.go
  utils/resultstable.go
  utils/resultstable_test.go
  utils/sarifutils.go
  utils/securityJobSummary.go
  utils/securityJobSummary_test.go
Labels: new feature

#65 Update dependencies
  go.mod
  go.sum
Labels: ignore for release

#59 Add warning and skip SCA scan when directory path doesn't exists
  commands/audit/scarunner.go
Labels: improvement

#10 Run contextual analysis and secret detection in Docker scans
  commands/audit/audit.go
  commands/audit/jasrunner.go
  commands/scan/dockerscan.go
  commands/scan/scan.go
  formats/conversion.go
  formats/table.go
  jas/applicability/applicabilitymanager.go
  jas/applicability/applicabilitymanager_test.go
  jas/common.go
  jas/common_test.go
  jas/commons_test.go
  jas/iac/iacscanner.go
  jas/iac/iacscanner_test.go
  jas/runner/jasrunner.go
  jas/runner/jasrunner_test.go
  jas/sast/sastscanner.go
  jas/sast/sastscanner_test.go
  jas/secrets/secretsscanner.go
  jas/secrets/secretsscanner_test.go
  jas/testdata/.jfrog/jfrog-apps-config.yml
  scans_test.go
Labels: new feature
