Repository jfrog/jfrog-cli-security, pull requests merged in 2024-07, with the labels that each got.

#97 Refactor artifactory utils
  commands/audit/scarunner.go
  commands/curation/curationaudit.go
  utils/artifactory/artifactoryutils.go
  utils/techutils/techutils.go
Labels: ignore for release

#101 Pass analytics env vars to analyzer manager
  jas/runner/jasrunner.go
Labels: bug

#102 Update dependencies
  .github/workflows/test.yml
  commands/audit/audit.go
  commands/scan/scan.go
  go.mod
  go.sum
  jas/analyzermanager.go
  jas/applicability/applicabilitymanager.go
  jas/common.go
  jas/common_test.go
  jas/iac/iacscanner.go
  jas/runner/jasrunner.go
  jas/runner/jasrunner_test.go
  jas/sast/sastscanner.go
  jas/secrets/secretsscanner.go
  utils/utils.go
  utils/utils_test.go
Labels: improvement

#105 Fix racing condition in SCA scan, assign third party deps
  commands/audit/scarunner.go
  go.mod
  go.sum
Labels: bug

#108 Update client-go to v1.41.2
  go.mod
  go.sum
Labels: improvement

#83 Add consistent behavior to table sorting in jf scan and jf audit
  utils/jasutils/jasutils.go
  utils/resultstable.go
Labels: improvement

#106 Fixing return url from build scan to be the CLI config url
  commands/scan/buildscan.go
  commands/scan/buildscan_test.go
Labels: bug

#100 Add support for CLI TLS in xraymanager and xscmanager
  utils/xray/xraymanager.go
  utils/xsc/xscmanager.go
Labels: bug

#81 SBOM ingestion
  cli/docs/enrich/help.go
  cli/docs/flags.go
  cli/scancommands.go
  commands/enrich/enrich.go
  commands/enrich/enrichgraph/enrichgraph.go
  commands/enrich/enrichgraph/params.go
  enrich_test.go
  formats/enrich_formats.go
  go.mod
  go.sum
  tests/testdata/other/enrich/enrich.json
  tests/testdata/other/enrich/enrich.xml
  tests/utils/test_utils.go
  utils/resultwriter.go
Labels: new feature

#109 Add 'input-file' option to git count command.
  cli/docs/flags.go
  cli/gitcommands.go
  cli/gitcommands_test.go
  commands/git/countcontributors.go
  commands/git/countcontributors_test.go
  git_test.go
  go.mod
  go.sum
  tests/testdata/git/inputfiles/bad_scm_type.yaml
  tests/testdata/git/inputfiles/empty_list.yaml
  tests/testdata/git/inputfiles/multiple_servers.yaml
  tests/testdata/git/inputfiles/one_server.yaml
Labels: improvement

#113 error for no results from xray graph scan in sbom-enrich should be more generic (not always its file problems)
  commands/enrich/enrich.go
Labels: ignore for release

#114 Update dependencies
  go.mod
  go.sum
Labels: improvement

#116 Update security commands categories
  cli/cli.go
  cli/scancommands.go
  go.mod
  go.sum
Labels: improvement

#112 Curation pip fix - Upgrade pip within the virtual env
  commands/audit/sca/python/python.go
Labels: bug

#111 Curation support for GitHub summary
  commands/curation/curationaudit.go
  commands/curation/curationaudit_test.go
  formats/summary.go
  tests/testdata/other/jobSummary/multi_command_job.md
  utils/securityJobSummary.go
  utils/securityJobSummary_test.go
Labels: improvement

#110 Update yarn apis
  commands/audit/sca/yarn/yarn.go
  go.mod
  go.sum
Labels: ignore for release

#117 Update Analyzer Manager to v1.8.9
  jas/analyzermanager.go
Labels: improvement

#121 Update Jfrog dependencies
  go.mod
  go.sum
Labels: improvement
