Repository jfrog/jfrog-cli-security, pull requests merged in 2024-10, with the labels that each got.

#191 Skip Auto-installation in Audit SCA scan if requested by user (Yarn, NPM, Go)
  cli/docs/flags.go
  cli/scancommands.go
  commands/audit/sca/npm/npm.go
  commands/audit/sca/npm/npm_test.go
  commands/audit/sca/yarn/yarn.go
  commands/audit/sca/yarn/yarn_test.go
  commands/audit/scarunner.go
  commands/curation/curationaudit.go
  go.mod
  go.sum
  utils/auditbasicparams.go
Labels: new feature

#200 Enable allow-partial-results for Audit SCA scan and dep tree construction
  cli/docs/flags.go
  cli/scancommands.go
  commands/audit/audit.go
  commands/audit/audit_test.go
  commands/audit/scarunner.go
  tests/testdata/projects/package-managers/npm/npm-un-installable/package.json
  utils/auditbasicparams.go
  utils/results.go
Labels: new feature

#204 Update dependencies for release
  go.mod
  go.sum
Labels: ignore for release

#206 Improve SAST results in SARIF format
  commands/audit/audit.go
  go.mod
  go.sum
  jas/analyzermanager.go
  jas/runner/jasrunner.go
  jas/sast/sastscanner.go
  jas/sast/sastscanner_test.go
  tests/testdata/other/sast-scan/contains-sast-violations.sarif
  tests/testdata/other/sast-scan/no-violations.sarif
  tests/testdata/output/audit/audit_results.json
  tests/testdata/output/audit/audit_sarif.json
  tests/testdata/projects/jas/jas-config/sast/result.sarif
  tests/testdata/projects/jas/jas/sast/result.sarif
  utils/results/output/resultwriter.go
  utils/validations/test_validate_sarif.go
Labels: improvement

#213 update AM to 1.9.11
  jas/analyzermanager.go
Labels: improvement

#205 Audit - Do not copy Visual Studio inner folder when building dependency tree
  commands/audit/sca/common.go
  commands/audit/sca/nuget/nuget.go
  commands/audit/sca/pnpm/pnpm.go
  commands/audit/sca/python/python.go
Labels: ignore for release

#160 Validate xray url
  audit_test.go
  jas/analyzermanager.go
  jas/common.go
  jas/common_test.go
  scans_test.go
  tests/utils/test_config.go
  tests/utils/test_utils.go
Labels: bug

#217 Support Linux ARM - Am version 1 11 1
  jas/analyzermanager.go
Labels: improvement
