Repository jfrog/jfrog-cli-security, pull requests merged in 2024-08, with the labels that each got.

#123 Scan - Wait for AnalyzerManager to finish download before scan
  commands/scan/scan.go
Labels: bug

#129 fix SARIF format security-severity attribute
  jas/common.go
  jas/common_test.go
Labels: bug

#131 Update AnalyzerManager to v1.8.10
  jas/analyzermanager.go
Labels: improvement

#84 JFrog CLI encodes the ignore url in on-demand scan result
  utils/resultwriter.go
  utils/resultwriter_test.go
Labels: bug

#132 Add option to run locally docker scan in the repo
  audit_test.go
  cli/scancommands.go
  jfrogclisecurity.go
  scans_test.go
  tests/utils/test_utils.go
Labels: ignore for release

#134 Update dependencies
  go.mod
  go.sum
Labels: improvement

#127 Issue in build scan result_url when JFrog URL is not configured
  commands/scan/buildscan.go
  commands/scan/buildscan_test.go
Labels: bug

#133 Add option to include vulnerabilities if violation context exists
  audit_test.go
  cli/docs/flags.go
  cli/scancommands.go
  scans_test.go
  xsc_test.go
Labels: improvement

#136 Implement 'BuildDependencyTree' for Conan
  .github/workflows/test.yml
  commands/audit/sca/conan/conan.go
  commands/audit/sca/conan/conan_test.go
  tests/testdata/other/conan/dependencies.json
  tests/testdata/projects/package-managers/conan/conanfile.txt
  utils/techutils/techutils.go
Labels: ignore for release

#126 add missing fields for operational risk in simpliftViolations functio…
  utils/resultstable.go
  utils/resultstable_test.go
Labels: bug

#140 Fix issues from PR #136
  .github/workflows/test.yml
  commands/audit/sca/conan/conan.go
  commands/audit/sca/conan/conan_test.go
  tests/testdata/projects/package-managers/conan/profile
  utils/auditbasicparams.go
Labels: bug

#139 fix flaky test results in TestOperationalRiskSimplifiedViolation test…
  utils/resultstable_test.go
Labels: ignore for release

#141 Fix SetConanProfile
  .github/workflows/test.yml
Labels: ignore for release

#142 Update Analyzer Manager to v1.8.13
  jas/analyzermanager.go
  jas/common.go
Labels: improvement

#147 fix static analysis test
  commands/curation/curationaudit.go
  commands/enrich/enrich.go
  commands/git/countcontributors.go
  commands/scan/downloadindexer.go
  commands/scan/scan.go
  commands/xray/offlineupdate/offlineupdate.go
  formats/sarifutils/sarifutils.go
  utils/severityutils/severity.go
Labels: ignore for release

#145 add xsc analytics to docker-scan command
  cli/scancommands.go
  commands/audit/audit.go
  commands/scan/dockerscan.go
  commands/scan/scan.go
  utils/xsc/xscmanager.go
  xsc_test.go
Labels: improvement

#149 Hide git namespace
  cli/cli.go
Labels: ignore for release

#135 Support Curation to run after package manager installation failure
  cli/scancommands.go
  cli/scancommands_test.go
  commands/audit/sca/common.go
  commands/audit/sca/common_test.go
  commands/audit/sca/go/golang.go
  commands/audit/sca/java/mvn.go
  commands/audit/sca/python/python.go
  commands/curation/curationaudit.go
  go.mod
  go.sum
  jas/analyzermanager.go
  jas/common.go
  tests/testdata/projects/package-managers/npm/npm-project/.jfrog/jfrog-cli.conf.v6
  utils/utils.go
Labels: new feature

#152 Fix conan tests
  cli/cli.go
  commands/audit/sca/conan/conan_test.go
  tests/testdata/other/conan/dependencies.json
Labels: ignore for release

#148 Use project env val in commands
  cli/scancommands.go
  commands/audit/audit.go
  go.mod
  go.sum
Labels: bug

#158 Fix CA NotCovered python status tests
  audit_test.go
Labels: ignore for release

#156 Upgrading AnalyzerManager version to 1.8.14
  jas/analyzermanager.go
Labels: ignore for release

#137 Improve Job Summary
  cli/scancommands.go
  cli/scancommands_test.go
  commands/curation/curationaudit.go
  commands/curation/curationaudit_test.go
  commands/scan/buildscan.go
  commands/scan/dockerscan.go
  commands/scan/scan.go
  formats/summary.go
  formats/summary_test.go
  go.mod
  go.sum
  resources/resources.go
  resources/statusIcons/failed.svg
  resources/statusIcons/passed.svg
  tests/testdata/other/jobSummary/binary_vulnerabilities.md
  tests/testdata/other/jobSummary/build_scan_vulnerabilities.md
  tests/testdata/other/jobSummary/docker_vulnerabilities.md
  tests/testdata/other/jobSummary/multi_command_job.md
  tests/testdata/other/jobSummary/no_violations.md
  tests/testdata/other/jobSummary/no_vulnerabilities.md
  tests/testdata/other/jobSummary/security_section.md
  tests/testdata/other/jobSummary/single_issue.md
  tests/testdata/other/jobSummary/single_no_issue.md
  tests/testdata/other/jobSummary/violations.md
  tests/testdata/other/jobSummary/violations_not_defined.md
  tests/testdata/other/jobSummary/violations_not_extended_view.md
  utils/results.go
  utils/results_test.go
  utils/resultstable.go
  utils/resultwriter.go
  utils/resultwriter_test.go
  utils/securityJobSummary.go
  utils/securityJobSummary_test.go
  utils/severityutils/severity.go
  utils/test_mocks.go
  utils/utils.go
  utils/xsc/analyticsmetrics.go
Labels: improvement
