Repository jfrog/jfrog-cli-security, pull requests merged in 2024-02, with the labels that each got.

#19 Show analyzerManager logs in CI
  utils/analyzermanager.go
Labels: improvement

#8 Contribution guide
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
Labels: ignore for release

#13 Support maven cli for curation cli cmd.
  cli/scancommands.go
  commands/audit/sca/common_test.go
  commands/audit/sca/npm/npm.go
  commands/audit/sca/nuget/nuget.go
  commands/audit/sca/yarn/yarn.go
  commands/audit/scarunner.go
  commands/curation/curationaudit.go
  commands/curation/curationaudit_test.go
  go.mod
  go.sum
  utils/auditbasicparams.go
  utils/paths.go
Labels: improvement

#18 Audit - Support Pnpm SCA scan
  .github/workflows/test.yml
  audit_test.go
  cli/docs/flags.go
  commands/audit/audit.go
  commands/audit/sca/common.go
  commands/audit/sca/npm/npm.go
  commands/audit/sca/pnpm/pnpm.go
  commands/audit/sca/pnpm/pnpm_test.go
  commands/audit/scarunner.go
  go.mod
  go.sum
Labels: improvement

#21 Deleted setProxy logic from audit files and changed flow to use new function in cli-core
  commands/audit/sca/go/golang.go
  go.mod
  go.sum
Labels: ignore for release

#25 Update dependencies before release
  go.mod
  go.sum
Labels: ignore for release

#26 Update Go version to 1.21
  .github/workflows/analysis.yml
  .github/workflows/test.yml
  go.mod
  go.sum
Labels: improvement

#28 Update build-info-go jfrog-client-go and jfrog-cli-core
  go.mod
  go.sum
Labels: improvement

#24 Use exclude pattern when building dotnet dependency tree
  cli/docs/flags.go
  cli/scancommands.go
  commands/audit/audit.go
  commands/audit/auditparams.go
  commands/audit/sca/common.go
  commands/audit/sca/common_test.go
  commands/audit/sca/nuget/nuget.go
  commands/audit/sca/nuget/nuget_test.go
  commands/audit/scarunner.go
  commands/audit/scarunner_test.go
  go.mod
  go.sum
  utils/auditbasicparams.go
Labels: bug
