Repository jfrog/jfrog-cli-security, pull requests merged in 2024-06, with the labels that each got.

#72 Print command output in nuget test
  audit_test.go
Labels: ignore for release

#74 add test for audit with watch flag
  audit_test.go
  commands/scan/scan.go
  jas/applicability/applicabilitymanager.go
  jas/secrets/secretsscanner.go
  scans_test.go
  tests/utils/test_utils.go
  tests/utils/test_validation.go
  xsc_test.go
Labels: ignore for release

#76 Update Go version to 1.22.3
  .github/workflows/analysis.yml
  .github/workflows/test.yml
  go.mod
  go.sum
Labels: improvement

#75 pyproject.toml can be used in Pip tech
  cli/scancommands.go
  cli/xraycommands.go
  commands/audit/sca/common.go
  commands/audit/sca/common_test.go
  commands/audit/sca/java/deptreemanager.go
  commands/audit/sca/java/mvn.go
  commands/audit/sca/python/python.go
  commands/audit/sca/python/python_test.go
  commands/audit/scarunner.go
  commands/audit/scarunner_test.go
  commands/curation/curationaudit.go
  commands/curation/curationaudit_test.go
  commands/scan/scan.go
  formats/simplejsonapi.go
  jas/applicability/applicabilitymanager.go
  jas/applicability/applicabilitymanager_test.go
  jas/common.go
  jas/common_test.go
  jas/runner/jasrunner.go
  jas/runner/jasrunner_test.go
  utils/results.go
  utils/resultstable.go
  utils/resultwriter.go
  utils/resultwriter_test.go
  utils/techutils.go
  utils/techutils/techutils.go
  utils/techutils/techutils_test.go
  utils/techutils_test.go
Labels: bug

#78 Show image name as target for command summary in docker scan cmd
  commands/scan/dockerscan.go
  commands/scan/scan.go
Labels: bug

#77 Always show relative target on command summary
  utils/securityJobSummary.go
  utils/securityJobSummary_test.go
Labels: bug

#79 Fix some bugs in latest PR
  commands/scan/dockerscan.go
  commands/scan/scan.go
Labels: ignore for release

#33 Running jas scanners in parallel
  .github/workflows/test.yml
  artifactory_test.go
  audit_test.go
  cli/docs/flags.go
  cli/scancommands.go
  commands/audit/audit.go
  commands/audit/auditparams.go
  commands/audit/sca/common.go
  commands/audit/scarunner.go
  commands/curation/curationaudit.go
  commands/scan/buildscan.go
  commands/scan/scan.go
  jas/applicability/applicabilitymanager.go
  jas/applicability/applicabilitymanager_test.go
  jas/common.go
  jas/common_test.go
  jas/commons_test.go
  jas/iac/iacscanner.go
  jas/iac/iacscanner_test.go
  jas/runner/jasrunner.go
  jas/runner/jasrunner_test.go
  jas/sast/sastscanner.go
  jas/sast/sastscanner_test.go
  jas/secrets/secretsscanner.go
  jas/secrets/secretsscanner_test.go
  scangraph/params.go
  tests/testdata/projects/empty_project/python_project_with_no_deps/main.py
  utils/analyticsmetrics.go
  utils/analyticsmetrics_test.go
  utils/analyzermanager.go
  utils/auditbasicparams.go
  utils/parallel_runner.go
  utils/results.go
  utils/results_test.go
  utils/resultwriter.go
  utils/resultwriter_test.go
  utils/sarifutils.go
  utils/securityJobSummary.go
Labels: improvement

#88 Fix resolving Maven dependency tree with snapshot versions
  artifactory_test.go
  commands/audit/sca/java/mvn.go
  commands/audit/sca/java/mvn_test.go
  commands/audit/sca/java/resources/settings.xml
  tests/consts.go
  tests/testdata/artifactory-repo-configs/maven_remote_snapshots_repository_config.json
  tests/testdata/artifactory-repo-configs/maven_virtual_repository_config.json
  tests/testdata/projects/package-managers/maven/maven-snapshot/pom.xml
Labels: bug

#85 Add option to run only specific sub scan
  cli/docs/flags.go
  cli/scancommands.go
  commands/audit/audit.go
  commands/audit/scarunner.go
  commands/scan/scan.go
  jas/runner/jasrunner.go
  jas/runner/jasrunner_test.go
  utils/auditbasicparams.go
  utils/resultwriter.go
  utils/utils.go
Labels: new feature

#90 Audit - Fix panic when platform has no JAS
  audit_test.go
  cli/docs/flags.go
  cli/scancommands.go
  commands/audit/audit.go
  scans_test.go
  tests/utils/test_config.go
  tests/utils/test_utils.go
  utils/auditbasicparams.go
Labels: ignore for release

#87 Audit - Control Pip install cmd with custom args
  commands/audit/sca/python/python.go
  commands/audit/sca/python/python_test.go
  commands/audit/scarunner.go
  tests/testdata/projects/package-managers/python/pip/pip/referenceproject/requirements.txt
Labels: improvement

#94 Use AnalyzerManager v1.8.3
  utils/analyzermanager.go
Labels: ignore for release

#95 Convert file exclusion for directory exclusion for JAS scanners
  cli/docs/flags.go
  commands/audit/sca/common.go
  jas/common.go
  jas/common_test.go
Labels: bug

#91 Add new git "count-contributors" command.
  cli/cli.go
  cli/docs/flags.go
  cli/docs/git/help.go
  cli/gitcommands.go
  commands/git/countcontributors.go
  commands/git/countcontributors_test.go
  git_test.go
  go.mod
  go.sum
Labels: new feature
