Repository jfrog/jfrog-cli-security, pull requests merged in 2024-12, with the labels that each got.

#254 Move skip tests calls
  audit_test.go
  scans_test.go
Labels: ignore for release

#256 Don't save SecurityCommandResults obj as a file
  utils/results/output/resultwriter.go
Labels: ignore for release

#262 Pass versions to conditional scans
  cli/scancommands.go
  commands/scan/scan.go
  utils/xsc/xscmanager.go
Labels: bug

#260 Update am 1.12.2 - SEC FP/FN
  jas/analyzermanager.go
Labels: improvement

#202 Control the depth of the pnpm dependency tree
  cli/docs/flags.go
  cli/scancommands.go
  commands/audit/sca/pnpm/pnpm.go
  commands/audit/sca/pnpm/pnpm_test.go
  tests/testdata/projects/package-managers/npm/npm-big-tree/package.json
  utils/auditbasicparams.go
Labels: improvement

#263 Add Mono download to linux test env
  .github/actions/install-and-setup/action.yml
  commands/audit/scarunner.go
Labels: ignore for release

#268 Fix issue in test
  tests/testdata/projects/package-managers/npm/npm-un-installable/package.json
Labels: ignore for release

#265 Initiate error upon partial missing components when constructing Yarn V1 dep tree
  commands/audit/sca/yarn/yarn.go
  commands/audit/sca/yarn/yarn_test.go
  go.mod
  go.sum
Labels: ignore for release

#261 Config profile with repo API implementation
  go.mod
  go.sum
  utils/validations/test_mocks.go
  utils/xsc/configprofile.go
  utils/xsc/configprofile_test.go
Labels: ignore for release

#270 Add output analytics for GH integration
  commands/scan/buildscan.go
  commands/scan/scan.go
  jas/common_test.go
  tests/testdata/output/jobSummary/binary_analytics_vulnerabilities.md
  tests/testdata/output/jobSummary/build_scan_analytics_vulnerabilities.md
  tests/testdata/output/jobSummary/violations.md
  tests/testdata/output/jobSummary/violations_analytics.md
  tests/testdata/output/jobSummary/violations_not_extended_view.md
  utils/formats/sarifutils/sarifutils.go
  utils/formats/sarifutils/sarifutils_test.go
  utils/formats/sarifutils/test_sarifutils.go
  utils/results/common_test.go
  utils/results/conversion/convertor.go
  utils/results/conversion/sarifparser/sarifparser.go
  utils/results/conversion/sarifparser/sarifparser_test.go
  utils/results/conversion/simplejsonparser/simplejsonparser_test.go
  utils/results/output/resultwriter.go
  utils/results/output/securityJobSummary.go
  utils/results/output/securityJobSummary_test.go
  utils/utils.go
Labels: improvement

#272 Escape Job-Id for url
  go.mod
  go.sum
  tests/testdata/output/jobSummary/binary_analytics_vulnerabilities.md
  tests/testdata/output/jobSummary/build_scan_analytics_vulnerabilities.md
  tests/testdata/output/jobSummary/violations_analytics.md
  utils/results/conversion/sarifparser/sarifparser.go
  utils/results/conversion/sarifparser/sarifparser_test.go
  utils/results/output/securityJobSummary.go
  utils/results/output/securityJobSummary_test.go
Labels: bug

#231 Swift support audit
  .github/actions/install-and-setup/action.yml
  .github/workflows/test.yml
  audit_test.go
  commands/audit/sca/cocoapods/podcommand.go
  commands/audit/sca/swift/swift.go
  commands/audit/sca/swift/swift_test.go
  commands/audit/sca/swift/swiftcommand.go
  commands/audit/scarunner.go
  tests/config.go
  tests/testdata/projects/package-managers/swift/Package.resolved
  tests/testdata/projects/package-managers/swift/Package.swift
  tests/utils/integration/test_integrationutils.go
  utils/auditbasicparams.go
  utils/techutils/techutils.go
  utils/xray/scangraph/scangraph.go
Labels: new feature
