Repository jfrog/jfrog-cli-security, pull requests merged in 2024-09, with the labels that each got.

#163 Print both vulnerabilities and violations tables if needed
  commands/audit/audit.go
  commands/scan/buildscan.go
  commands/scan/dockerscan.go
  commands/scan/scan.go
  utils/resultwriter.go
Labels: bug

#164 Fix sorting table results when no JAS scan
  utils/resultwriter_test.go
  utils/severityutils/severity.go
Labels: bug

#146 Added centralized config utilization in Audit for CI Next
  commands/audit/audit.go
  commands/audit/audit_test.go
  commands/audit/auditparams.go
  commands/audit/scarunner.go
  commands/scan/scan.go
  jas/runner/jasrunner.go
  jas/runner/jasrunner_test.go
  tests/testdata/other/configProfile/configProfileExample.json
  utils/test_mocks.go
  utils/xsc/configprofile.go
  utils/xsc/configprofile_test.go
  utils/xsc/errorreport.go
  utils/xsc/xscmanager.go
Labels: ignore for release

#138 Record SARIF results after security commands to upload for GitHub
  commands/audit/audit.go
  commands/curation/curationaudit.go
  commands/curation/curationaudit_test.go
  commands/enrich/enrich.go
  commands/scan/buildscan.go
  commands/scan/dockerscan.go
  commands/scan/scan.go
  formats/sarifutils/sarifutils.go
  formats/sarifutils/sarifutils_test.go
  formats/sarifutils/test_sarifutils.go
  go.mod
  go.sum
  tests/testdata/other/jobSummary/security_section.md
  tests/testdata/other/jobSummary/violations_not_extended_view.md
  utils/paths.go
  utils/results.go
  utils/resultstable.go
  utils/resultstable_test.go
  utils/resultwriter.go
  utils/resultwriter_test.go
  utils/securityJobSummary.go
  utils/securityJobSummary_test.go
  utils/utils.go
Labels: new feature

#166 Disable generating SARIF for GitHub advance security tab if not entitled for JAS
  utils/securityJobSummary.go
  utils/securityJobSummary_test.go
Labels: improvement

#169 Add fingerprint field to simple json format
  formats/sarifutils/sarifutils.go
  formats/sarifutils/sarifutils_test.go
  formats/sarifutils/test_sarifutils.go
  formats/simplejsonapi.go
  utils/jasutils/jasutils.go
  utils/resultstable.go
Labels: improvement

#170 Add legal info message to git count command and change flags to manda…
  cli/docs/flags.go
  commands/git/countcontributors.go
  git_test.go
Labels: ignore for release

#174 Update Dependencies
  go.mod
  go.sum
Labels: improvement

#155 Undetermined reason for undetermined contextual analysis status
  formats/sarifutils/sarifutils.go
  formats/sarifutils/test_sarifutils.go
  formats/simplejsonapi.go
  utils/resultstable.go
  utils/resultstable_test.go
  utils/resultwriter_test.go
Labels: improvement

#168 Dumping scan results to local dir
  cli/docs/flags.go
  cli/scancommands.go
  commands/audit/audit.go
  commands/audit/audit_test.go
  commands/audit/auditparams.go
  commands/audit/scarunner.go
  commands/scan/scan.go
  jas/runner/jasrunner.go
  jas/runner/jasrunner_test.go
  tests/testdata/other/graphScanResults/graphScanResult.txt
  utils/test_mocks.go
  utils/utils.go
Labels: new feature

#172 Fix build scan command output in table format
  commands/scan/buildscan.go
  utils/securityJobSummary.go
Labels: bug

#175 Improved tech detection when tech is provided by user
  utils/techutils/techutils.go
  utils/techutils/techutils_test.go
Labels: improvement

#179 Fixed wrong root identification in module detection
  utils/techutils/techutils.go
  utils/techutils/techutils_test.go
Labels: bug

#153 Missing context new status for CA
  audit_test.go
  jas/analyzermanager.go
  jas/applicability/applicabilitymanager_test.go
  tests/testdata/other/applicability-scan/new_ca_status.sarif
  tests/testdata/projects/package-managers/go/missing-context/go.mod
  tests/testdata/projects/package-managers/go/missing-context/go.sum
  tests/utils/test_validation.go
  utils/jasutils/jasutils.go
  utils/resultstable.go
  utils/resultstable_test.go
  utils/resultwriter_test.go
  utils/severityutils/severity.go
  utils/xray/scangraph/scangraph_test.go
Labels: improvement

#144 Secret Token Validation feature
  audit_test.go
  cli/docs/flags.go
  cli/scancommands.go
  commands/audit/audit.go
  commands/audit/audit_test.go
  commands/scan/scan.go
  formats/conversion.go
  formats/sarifutils/sarifutils.go
  formats/sarifutils/test_sarifutils.go
  formats/simplejsonapi.go
  formats/table.go
  jas/analyzermanager.go
  jas/common.go
  jas/common_test.go
  jas/runner/jasrunner_test.go
  scans_test.go
  tests/config.go
  tests/testdata/other/enrich/enrich.json
  tests/testdata/other/enrich/enrich.xml
  tests/testdata/projects/jas/jas/secrets/api_secrets/tokens
  tests/utils/test_validation.go
  utils/jasutils/jasutils.go
  utils/results.go
  utils/resultstable.go
  utils/resultstable_test.go
  utils/resultwriter.go
  utils/utils.go
Labels: new feature

#180 Improved error message
  utils/xsc/configprofile.go
Labels: ignore for release

#183 Update dependencies
  audit_test.go
  commands/audit/audit_test.go
  go.mod
  go.sum
  jas/analyzermanager.go
Labels: improvement

#185 Show only requested scanners in SARIF format
  commands/scan/dockerscan.go
  commands/scan/scan.go
  utils/resultwriter.go
  utils/securityJobSummary.go
  utils/securityJobSummary_test.go
Labels: bug

#189 Add logs and add error if serverDetails not provided
  commands/audit/audit.go
  commands/scan/scan.go
  jas/analyzermanager.go
  jas/common.go
  jas/runner/jasrunner.go
  jas/runner/jasrunner_test.go
Labels: bug

#190 Update Dependencies
  go.mod
  go.sum
Labels: improvement

#192 Apply Min-Severity filter on Jas results
  commands/audit/audit.go
  commands/scan/scan.go
  jas/applicability/applicabilitymanager.go
  jas/applicability/applicabilitymanager_test.go
  jas/common.go
  jas/iac/iacscanner.go
  jas/iac/iacscanner_test.go
  jas/runner/jasrunner_test.go
  jas/sast/sastscanner.go
  jas/sast/sastscanner_test.go
  jas/secrets/secretsscanner.go
  jas/secrets/secretsscanner_test.go
  tests/testdata/other/secrets-scan/contain-secrets.sarif
Labels: bug

#193 Update CLA assistant
  .github/workflows/cla.yml
  jas/common.go
Labels: ignore for release

#194 Update AnalyzerManager
  go.mod
  go.sum
  jas/analyzermanager.go
Labels: improvement
