Repository jfrog/jfrog-cli-security, pull requests merged in 2024-03, with the labels that each got.

#31 Curation mvn enabled
  commands/curation/curationaudit.go
  commands/curation/curationaudit_test.go
  go.mod
  go.sum
  tests/testdata/projects/package-managers/maven/maven-curation/pretest/pom.xml
  tests/testdata/projects/package-managers/maven/maven-curation/test/.jfrog/projects/maven.yaml
  tests/testdata/projects/package-managers/maven/maven-curation/test/pom.xml
  utils/paths.go
Labels: improvement

#35 Curation - Generate a cache directory dedicated to each project
  commands/audit/scarunner.go
  commands/curation/curationaudit_test.go
  utils/paths.go
Labels: improvement

#40 Fix testdata project path in Yarn tests
  commands/audit/sca/yarn/yarn_test.go
Labels: bug

#42 Update dependencies for release
  go.mod
  go.sum
Labels: ignore for release

#44 Move Java Dep Tree content from Core
  .github/workflows/embedded-jar-test.yml
  buildscripts/download-jars.sh
  commands/audit/sca/java/deptreemanager.go
  commands/audit/sca/java/deptreemanager_test.go
  commands/audit/sca/java/gradle.go
  commands/audit/sca/java/gradle_test.go
  commands/audit/sca/java/mvn.go
  commands/audit/sca/java/mvn_test.go
  commands/audit/sca/java/resources/gradle-dep-tree.jar
  commands/audit/sca/java/resources/maven-dep-tree.jar
  commands/audit/sca/java/resources/settings.xml
  commands/audit/scarunner.go
  tests/testdata/projects/package-managers/maven/maven-example-with-many-types/pom.xml
Labels: ignore for release

#43 Audit - Fix UseWrapper for Gradle/Maven dep tree
  commands/audit/scarunner.go
  go.mod
  go.sum
Labels: bug

#41 Additions to support Pnpm in frogbot
  commands/audit/sca/pnpm/pnpm.go
  commands/audit/sca/pnpm/pnpm_test.go
Labels: ignore for release

#48 Update core and client-go versions
  go.mod
  go.sum
Labels: improvement
