Repository jfrog/jfrog-cli-security, pull requests merged in 2024-11, with the labels that each got.

#214 Apply skip-auto-install on NuGet/.Net projects
  commands/audit/sca/nuget/nuget.go
  commands/audit/sca/nuget/nuget_test.go
Labels: improvement

#162 Improve Tests
  .github/PULL_REQUEST_TEMPLATE.md
  .github/actions/install-and-setup/action.yml
  .github/workflows/analysis.yml
  .github/workflows/removeLabel.yml
  .github/workflows/test.yml
  CONTRIBUTING.md
  _typos.toml
  artifactory_test.go
  audit_test.go
  cli/docs/flags.go
  cli/gitcommands.go
  commands/audit/audit.go
  commands/audit/audit_test.go
  commands/audit/sca/java/mvn.go
  commands/audit/sca/nuget/nuget.go
  commands/audit/sca/pnpm/pnpm.go
  commands/audit/sca/python/python.go
  commands/audit/scarunner.go
  commands/curation/curationaudit.go
  commands/curation/curationaudit_test.go
  commands/enrich/enrich.go
  commands/git/countcontributors.go
  commands/scan/buildscan.go
  commands/scan/scan.go
  enrich_test.go
  git_test.go
  jas/common.go
  jas/runner/jasrunner.go
  jas/runner/jasrunner_test.go
  jfrogclisecurity_test.go
  scans_test.go
  tests/config.go
  tests/consts.go
  tests/testdata/projects/package-managers/go/missing-context/go.mod
  tests/testdata/projects/package-managers/go/missing-context/go.sum
  tests/testdata/projects/package-managers/maven/missing-context/pom.xml
  tests/utils/integration/test_integrationutils.go
  tests/utils/test_utils.go
  unit_test.go
  utils/parallel_runner.go
  utils/results/conversion/convertor.go
  utils/results/conversion/sarifparser/sarifparser.go
  utils/results/conversion/simplejsonparser/simplejsonparser.go
  utils/results/conversion/summaryparser/summaryparser.go
  utils/results/conversion/tableparser/tableparser.go
  utils/results/results.go
  utils/xsc/analyticsmetrics_test.go
  utils/xsc/errorreport.go
  utils/xsc/errorreport_test.go
  utils/xsc/xscmanager.go
  xray_test.go
  xsc_test.go
Labels: ignore for release

#218 Fix operation of scan skip flags
  jas/runner/jasrunner.go
Labels: bug

#220 Get Extended value for SARIF record
  .github/workflows/test.yml
  commands/scan/dockerscan.go
  commands/scan/scan.go
  go.mod
  go.sum
  utils/results/output/securityJobSummary.go
  utils/results/output/securityJobSummary_test.go
Labels: bug

#223 Apply allow-partial-results to JAS scans
  commands/audit/audit.go
  commands/audit/audit_test.go
  commands/scan/scan.go
  jas/runner/jasrunner.go
  utils/results/results.go
Labels: ignore for release

#226 Fix error handling issue
  jas/runner/jasrunner.go
Labels: ignore for release

#230 Add NoTech Technology for directories with no tech
  audit_test.go
  commands/audit/audit.go
  commands/audit/audit_test.go
  commands/audit/scarunner.go
  utils/results/results.go
  utils/techutils/techutils.go
  utils/techutils/techutils_test.go
Labels: bug

#229 Enable allow-partial-results to Yarn V1 dependencies map construction
  commands/audit/sca/yarn/yarn.go
  go.mod
  go.sum
  jas/analyzermanager.go
  utils/auditbasicparams.go
Labels: ignore for release

#196 Cocoapods support for audit
  .github/actions/install-and-setup/action.yml
  audit_test.go
  commands/audit/sca/cocoapods/cocoapods.go
  commands/audit/sca/cocoapods/cocoapods_test.go
  commands/audit/sca/cocoapods/podcommand.go
  commands/audit/scarunner.go
  tests/config.go
  tests/testdata/projects/package-managers/cocoapods/Podfile
  tests/testdata/projects/package-managers/cocoapods/Podfile.lock
  tests/testdata/projects/package-managers/cocoapods/Test.xcodeproj/project.pbxproj
  tests/utils/integration/test_integrationutils.go
  utils/techutils/techutils.go
Labels: new feature

#237 cocoapods-fix
  .github/workflows/test.yml
  commands/audit/sca/cocoapods/cocoapods_test.go
  tests/testdata/projects/package-managers/cocoapods/Podfile
  tests/testdata/projects/package-managers/cocoapods/Podfile.lock
  tests/testdata/projects/package-managers/cocoapods/Test.xcodeproj/project.pbxproj
Labels: ignore for release

#234 Fix bugs when converting results to SARIF
  tests/testdata/output/audit/audit_sarif.json
  tests/testdata/output/dockerscan/docker_results.json
  tests/testdata/output/dockerscan/docker_sarif.json
  utils/formats/sarifutils/sarifutils.go
  utils/results/conversion/sarifparser/sarifparser.go
  utils/results/conversion/sarifparser/sarifparser_test.go
  utils/validations/test_validate_sarif.go
Labels: bug

#235 Enable all scanners enablement/disablement through config profile
  commands/audit/audit_test.go
  commands/audit/scarunner.go
  jas/runner/jasrunner.go
  utils/validations/test_mocks.go
Labels: ignore for release

#243 Am 1.11.7 + Add dist to JAS exclusions
  jas/analyzermanager.go
  utils/utils.go
Labels: improvement

#244 Update AM to 1.11.8 - fix os for sast
  jas/analyzermanager.go
Labels: bug

#236 Align client-go - Xsc to Xray
  audit_test.go
  cli/scancommands.go
  commands/audit/audit.go
  commands/audit/audit_test.go
  commands/audit/auditparams.go
  commands/audit/sca/common.go
  commands/audit/scarunner.go
  commands/scan/dockerscan.go
  commands/scan/scan.go
  go.mod
  go.sum
  tests/utils/integration/test_integrationutils.go
  tests/utils/test_utils.go
  utils/auditbasicparams.go
  utils/results/results.go
  utils/validations/test_mocks.go
  utils/xray/scangraph/params.go
  utils/xray/scangraph/scangraph.go
  utils/xsc/analyticsmetrics.go
  utils/xsc/analyticsmetrics_test.go
  utils/xsc/configprofile.go
  utils/xsc/configprofile_test.go
  utils/xsc/errorreport.go
  utils/xsc/errorreport_test.go
  utils/xsc/xscmanager.go
  xsc_test.go
Labels: ignore for release

#238 License Violation - Show IssueId If LicenseKey is Empty
  utils/results/conversion/simplejsonparser/simplejsonparser.go
Labels: bug

#239 Remove 'Root' from license violation when Unknown enabled
  utils/results/common.go
Labels: bug

#248 Add 'dist' to the default exclusion patterns
  audit_test.go
  commands/audit/sca/common_test.go
  tests/testdata/projects/jas/jas/sast/flask_webgoat/dist/init_file_to_ignore.py
  tests/testdata/projects/package-managers/dotnet/dotnet-single/sample_sast_vulnerability.cs
  utils/utils.go
Labels: improvement

#249 Update Dependencies
  .github/actions/install-and-setup/action.yml
  audit_test.go
  commands/audit/sca/nuget/nuget.go
  commands/audit/sca/nuget/nuget_test.go
  commands/curation/curationaudit_test.go
  go.mod
  go.sum
Labels: improvement

#250 Update am version
  jas/analyzermanager.go
Labels: improvement

#252 Fix SCA scan issue with XSC and no analytics
  go.mod
  go.sum
  utils/xray/scangraph/scangraph.go
Labels: bug

#253 Scan - Add Xray version to Xray graph scan params
  .github/workflows/test.yml
  audit_test.go
  commands/scan/scan.go
  xsc_test.go
Labels: bug
