Repository jfrog/jfrog-cli-security, pull requests merged in 2025-06, with the labels that each got.

#465 Bugfix: bad server definition in mcp test
  commands/source_mcp/source_mcp_test.go
Labels: ignore for release

#456 Update dependencies due to adding support for multiple sources for create release bundle
  go.mod
  go.sum
Labels: ignore for release

#471 Add fail_pr in simple json conversion - Sca, Licences, IaC, Sast, Secrets
  utils/formats/sarifutils/sarifutils.go
  utils/formats/simplejsonapi.go
  utils/results/conversion/simplejsonparser/simplejsonparser.go
Labels: improvement

#476 Fix empty tree sent to SCA scan
  commands/audit/scarunner.go
Labels: bug

#473 Sca scan interface
  audit_test.go
  cli/gitcommands.go
  cli/scancommands.go
  cli/utils.go
  commands/audit/audit.go
  commands/audit/audit_test.go
  commands/audit/auditparams.go
  commands/audit/scarunner.go
  commands/enrich/enrich.go
  commands/git/audit/gitaudit.go
  commands/git/audit/gitauditparams.go
  commands/scan/buildscan.go
  commands/scan/scan.go
  jas/applicability/applicabilitymanager.go
  jas/applicability/applicabilitymanager_test.go
  jas/iac/iacscanner.go
  jas/runner/jasrunner.go
  jas/runner/jasrunner_test.go
  jas/sast/sastscanner.go
  jas/secrets/secretsscanner.go
  sca/bom/bomgenerator.go
  sca/bom/bomgenerator_test.go
  sca/bom/buildinfo/buildinfobom.go
  sca/bom/buildinfo/technologies/common.go
  sca/bom/indexer/indexerbom.go
  sca/scan/scangraph/runner.go
  sca/scan/scangraph/runner_test.go
  sca/scan/scascan.go
  tests/validations/test_mocks.go
  tests/validations/test_validate_sarif.go
  utils/formats/cdxutils/cyclonedxutils.go
  utils/formats/cdxutils/cyclonedxutils_test.go
  utils/results/common.go
  utils/results/common_test.go
  utils/results/conversion/convertor.go
  utils/results/conversion/convertor_test.go
  utils/results/conversion/sarifparser/sarifparser.go
  utils/results/conversion/simplejsonparser/simplejsonparser.go
  utils/results/conversion/summaryparser/summaryparser.go
  utils/results/conversion/tableparser/tableparser.go
  utils/results/results.go
  utils/severityutils/severity.go
  utils/severityutils/severity_test.go
  utils/techutils/techutils.go
  utils/utils.go
  utils/xsc/analyticsmetrics_test.go
Labels: ignore for release

#482 Pass project key to scan entitlements
  commands/scan/scan.go
Labels: bug
