Repository jfrog/jfrog-cli-security, pull requests merged in 2025-07, with the labels that each got.

#477 Upload cdx cmd
  artifactory_test.go
  audit_test.go
  cli/docs/flags.go
  cli/docs/upload/help.go
  cli/scancommands.go
  commands/upload/uploadcdx.go
  enrich_test.go
  sca/bom/buildinfo/technologies/swift/swift.go
  tests/consts.go
  tests/utils/integration/test_integrationutils.go
  utils/artifactory/artifactoryutils.go
  utils/path_test.go
  utils/paths.go
  utils/utils.go
  xray_test.go
Labels: ignore for release

#486 Fix generate URL after upload-cdx
  commands/upload/uploadcdx.go
  commands/upload/uploadcdx_test.go
  utils/artifactory/artifactoryutils.go
  utils/path_test.go
  utils/paths.go
  utils/utils.go
Labels: ignore for release

#481 Fix cocoapods dependency tree direct and transitive
  sca/bom/buildinfo/technologies/cocoapods/cocoapods.go
  sca/bom/buildinfo/technologies/cocoapods/cocoapods_test.go
Labels: bug

#475 Cyclonedx output format
  audit_test.go
  cli/docs/flags.go
  cli/scancommands.go
  commands/audit/audit.go
  commands/upload/uploadcdx_test.go
  git_test.go
  go.mod
  go.sum
  jas/runner/jasrunner.go
  sca/bom/buildinfo/buildinfobom.go
  sca/bom/indexer/indexerbom.go
  sca/scan/scascan.go
  scans_test.go
  tests/testdata/output/dockerscan/docker_simple_json.json
  tests/testdata/projects/jas/jas-npm/TOKENS
  tests/testdata/projects/jas/jas-npm/app.js
  tests/testdata/projects/jas/jas-npm/package-lock.json
  tests/testdata/projects/jas/jas-npm/package.json
  tests/utils/test_utils.go
  tests/validations/test_validate_cyclonedx.go
  tests/validations/test_validate_sarif.go
  utils/formats/cdxutils/cyclonedxutils.go
  utils/formats/cdxutils/cyclonedxutils_test.go
  utils/formats/sarifutils/sarifutils.go
  utils/formats/sarifutils/sarifutils_test.go
  utils/formats/sarifutils/test_sarifutils.go
  utils/jasutils/jasutils.go
  utils/path_test.go
  utils/paths.go
  utils/results/common.go
  utils/results/common_test.go
  utils/results/conversion/convertor.go
  utils/results/conversion/convertor_test.go
  utils/results/conversion/cyclonedxparser/cyclonedxparser.go
  utils/results/conversion/sarifparser/sarifparser.go
  utils/results/conversion/sarifparser/sarifparser_test.go
  utils/results/conversion/simplejsonparser/simplejsonparser.go
  utils/results/conversion/simplejsonparser/simplejsonparser_test.go
  utils/results/conversion/summaryparser/summaryparser.go
  utils/results/output/resultwriter.go
  utils/results/results.go
  utils/utils.go
  xsc_test.go
Labels: new feature

#478 Enrich SBOM strategy
  cli/utils.go
  commands/audit/audit.go
  commands/upload/uploadcdx_test.go
  go.mod
  go.sum
  sca/scan/enrich/runner.go
  sca/scan/scascan.go
  utils/catalog/catalogmanager.go
Labels: ignore for release

#494 Fix buildinfo pip root component
  sca/bom/buildinfo/technologies/python/python.go
  sca/bom/buildinfo/technologies/python/python_test.go
  sca/bom/scang/plugin/plugin.go
  tests/validations/test_validate_cyclonedx.go
  utils/formats/cdxutils/cyclonedxutils.go
  utils/formats/cdxutils/cyclonedxutils_test.go
  utils/results/common.go
Labels: ignore for release

#484 Gem-Dep-Tree-Creation
  sca/bom/buildinfo/technologies/gem/gem.go
  sca/bom/buildinfo/technologies/gem/gem_test.go
  tests/testdata/projects/package-managers/gem/Gemfile
  utils/techutils/techutils.go
Labels: ignore for release

#498 replace sast fingerprint to significant path
  utils/jasutils/jasutils.go
Labels: improvement

#459 Gem for Audit and Curation
  audit_test.go
  commands/curation/curationaudit.go
  commands/curation/curationaudit_test.go
  sca/bom/buildinfo/buildinfobom.go
  sca/bom/buildinfo/technologies/gem/gem.go
  tests/testdata/projects/package-managers/gem/audit-gem/Gemfile
  tests/testdata/projects/package-managers/gem/curation-project/.jfrog/projects/ruby.yaml
  tests/testdata/projects/package-managers/gem/curation-project/Gemfile
  utils/techutils/techutils.go
Labels: new feature

#207 Add insecure-tls flag support for all security commands
  cli/docs/flags.go
Labels: improvement

#516 fix conan build dep tree tests
  sca/bom/buildinfo/technologies/conan/conan_test.go
  tests/testdata/other/conan/dependencies.json
Labels: ignore for release
