Repository jfrog/jfrog-cli-security, pull requests merged in 2025-05, with the labels that each got.

#416 Fix Pnpm tests
  commands/audit/sca/pnpm/pnpm_test.go
Labels: ignore for release

#417 Fix Swift Flaky tests
  .github/actions/install-and-setup/action.yml
Labels: ignore for release

#412 Add an option to provide descriptor name in Conan graph info command
  commands/audit/sca/conan/conan.go
  commands/audit/sca/conan/conan_test.go
  commands/audit/scarunner.go
Labels: ignore for release

#423 Change froggit-go development branch comment
  go.mod
Labels: ignore for release

#420 :bug: Fix bug to use Maven wrapper when DepTreeParams.UseWrapper is true
  commands/audit/sca/java/mvn.go
Labels: bug

#422 BuildScan - Fix parse violations if requested to show
  utils/results/output/resultwriter.go
Labels: bug

#426 Update dependencies for support new lifecycle annotate command
  commands/audit/sca/java/mvn.go
  go.mod
  go.sum
  tests/testdata/projects/package-managers/go/curation-project/go.sum
Labels: ignore for release

#450 Update dependencies
  commands/audit/sca/python/python.go
  go.mod
  go.sum
  jas/analyzermanager.go
Labels: improvement

#451 Revert conan use of PipRequirementsFile
  commands/audit/sca/conan/conan.go
  commands/audit/sca/conan/conan_test.go
  commands/audit/scarunner.go
Labels: ignore for release

#453 Change nanopb version
  commands/audit/sca/cocoapods/cocoapods_test.go
  tests/testdata/projects/package-managers/cocoapods/Podfile
  tests/testdata/projects/package-managers/cocoapods/Podfile.lock
Labels: ignore for release

#389 Diff scan
  commands/audit/audit.go
  commands/audit/audit_test.go
  commands/audit/auditparams.go
  commands/audit/scarunner.go
  commands/audit/scarunner_test.go
  commands/curation/curationaudit.go
  commands/enrich/enrich.go
  commands/scan/buildscan.go
  commands/scan/scan.go
  jas/analyzermanager.go
  jas/applicability/applicabilitymanager.go
  jas/common.go
  jas/common_test.go
  jas/commons_test.go
  jas/iac/iacscanner.go
  jas/iac/iacscanner_test.go
  jas/runner/jasrunner.go
  jas/runner/jasrunner_test.go
  jas/sast/sastscanner.go
  jas/sast/sastscanner_test.go
  jas/secrets/secretsscanner.go
  jas/secrets/secretsscanner_test.go
  tests/validations/test_mocks.go
  utils/path_test.go
  utils/paths.go
  utils/results/common.go
  utils/results/common_test.go
  utils/results/conversion/convertor.go
  utils/results/conversion/convertor_test.go
  utils/results/results.go
  utils/techutils/techutils.go
  utils/utils.go
  utils/xsc/analyticsmetrics_test.go
  utils/xsc/configprofile_test.go
Labels: ignore for release

#455 Added curation audit for gradle
  commands/audit/sca/java/gradle.go
  commands/curation/curationaudit.go
  commands/curation/curationaudit_test.go
  tests/testdata/projects/package-managers/gradle/curation-project/.jfrog/projects/gradle.yaml
  tests/testdata/projects/package-managers/gradle/curation-project/build.gradle
  utils/auditbasicparams.go
Labels: new feature
