Repository jfrog/jfrog-cli-security, pull requests merged in 2025-01, with the labels that each got.

#276 Fix CI tests 'vars' value
  .github/workflows/test.yml
  utils/formats/summary.go
Labels: ignore for release, safe to test

#278 Add max-tree-depth flag to audit help
  cli/docs/flags.go
Labels: bug

#279 Use Technology in issue first
  tests/testdata/projects/package-managers/python/poetry/poetry-project/poetry.lock
  tests/testdata/projects/package-managers/python/poetry/poetry-project/pyproject.toml
  tests/testdata/projects/package-managers/python/poetry/poetry/pyproject.toml
  utils/results/common.go
  utils/results/conversion/simplejsonparser/simplejsonparser.go
Labels: bug

#275 Filter out non-applicable violations if requested by policy
  audit_test.go
  commands/audit/scarunner.go
  go.mod
  go.sum
  jas/runner/jasrunner.go
  tests/utils/test_utils.go
  utils/results/common.go
  utils/results/common_test.go
  utils/results/conversion/convertor_test.go
  utils/results/results.go
  xsc_test.go
Labels: improvement

#277 Add analytics pixel as prefix
  tests/testdata/output/jobSummary/binary_analytics_vulnerabilities.md
  tests/testdata/output/jobSummary/build_scan_analytics_vulnerabilities.md
  tests/testdata/output/jobSummary/violations_analytics.md
  utils/results/conversion/sarifparser/sarifparser.go
  utils/results/conversion/sarifparser/sarifparser_test.go
  utils/results/output/securityJobSummary.go
Labels: ignore for release

#271 Update dependencies
  commands/audit/sca/python/python.go
  go.mod
  go.sum
  jas/runner/jasrunner.go
  tests/utils/test_utils.go
  xsc_test.go
Labels: improvement

#274 swift improvement to fix tech
  commands/audit/sca/swift/swift.go
  commands/audit/sca/swift/swift_test.go
  tests/testdata/projects/package-managers/swift/Package.swift
Labels: ignore for release

#290 Don't download AM if JAS not requested
  commands/audit/audit.go
  utils/utils.go
Labels: bug

#286 Pass Technology of SCA scan
  commands/audit/sca/common.go
  commands/audit/scarunner.go
Labels: bug

#282 Show operational risk table even if empty
  utils/results/output/resultwriter.go
Labels: bug

#255 Don't clean sub directories if Tech not supporting Multi Module
  utils/techutils/techutils.go
  utils/techutils/techutils_test.go
Labels: bug

#289 Update Dependencies
  audit_test.go
  commands/audit/audit_test.go
  go.mod
  go.sum
  jas/analyzermanager.go
Labels: improvement

#284 Adding new fields to analytics finalize event report
  commands/audit/audit.go
  jas/common.go
  utils/utils.go
  utils/xsc/analyticsmetrics.go
  utils/xsc/analyticsmetrics_test.go
  xsc_test.go
Labels: ignore for release

#291 Send filename to xray on sbom-enrich api
  commands/enrich/enrich.go
  commands/enrich/enrichgraph/enrichgraph.go
  go.mod
  go.sum
Labels: improvement

#285 Git Audit Command
  .github/workflows/test.yml
  .gitignore
  audit_test.go
  cli/docs/flags.go
  cli/docs/git/audit/help.go
  cli/docs/git/contributors/help.go
  cli/gitcommands.go
  cli/scancommands.go
  cli/utils.go
  commands/audit/audit.go
  commands/git/audit/gitaudit.go
  commands/git/audit/gitauditparams.go
  commands/git/contributors/countcontributors.go
  commands/git/contributors/countcontributors_test.go
  git_test.go
  go.mod
  tests/testdata/git/projects/clean/clean.zip
  tests/testdata/git/projects/dirty/dirty.zip
  tests/testdata/git/projects/forked/forked.zip
  tests/testdata/git/projects/gitlab/gitlab.zip
  tests/testdata/git/projects/issues/issues.zip
  tests/testdata/git/projects/nogit/nogit.zip
  tests/testdata/git/projects/selfhosted/selfhosted.zip
  tests/utils/integration/test_integrationutils.go
  tests/utils/test_utils.go
  utils/gitutils/gitmanager.go
  utils/gitutils/gitmanager_test.go
  xsc_test.go
Labels: ignore for release

#293 Migrate artifactory commands from cli-core to cli-artifactory
  artifactory_test.go
  commands/audit/sca/go/golang.go
  commands/audit/sca/npm/npm.go
  commands/audit/sca/nuget/nuget.go
  commands/audit/sca/python/python.go
  commands/audit/sca/yarn/yarn.go
  go.mod
  go.sum
  scans_test.go
  tests/utils/integration/test_integrationutils.go
Labels: improvement
