Repository jfrog/jfrog-cli-security, pull requests merged in 2025-04, with the labels that each got.

#314 Integrating new Config Profile changes + Add support in scanners exclusions through profile
  commands/audit/audit.go
  commands/audit/audit_test.go
  commands/audit/auditparams.go
  commands/audit/sca/common.go
  commands/audit/sca/common_test.go
  commands/audit/scarunner.go
  go.mod
  go.sum
  jas/applicability/applicabilitymanager.go
  jas/common.go
  jas/common_test.go
  jas/iac/iacscanner.go
  jas/runner/jasrunner.go
  jas/sast/sastscanner.go
  jas/secrets/secretsscanner.go
  tests/testdata/other/configProfile/configProfileExample.json
  utils/auditbasicparams.go
  utils/xsc/configprofile.go
  utils/xsc/configprofile_test.go
Labels: improvement

#405 Swift error fix
  .github/actions/install-and-setup/action.yml
Labels: ignore for release

#400 Apply fail-build when violation context exists even with --vuln flag
  commands/audit/audit.go
  commands/scan/scan.go
  git_test.go
  scans_test.go
Labels: bug

#408 Add CVE attributes to simple json format
  utils/formats/simplejsonapi.go
  utils/results/common.go
  utils/results/conversion/simplejsonparser/simplejsonparser_test.go
Labels: improvement

#409 Update dependencies for 1.17.0 release
  go.mod
  go.sum
Labels: ignore for release

#411 Update Analyzer Manager to v1.17.0
  jas/analyzermanager.go
Labels: improvement
