Repository jfrog/jfrog-cli-security, pull requests merged in 2025-08, with the labels that each got.

#515 GitHub Dependency Submission: SBOM to Snapshot convertor
  utils/formats/snapshotconvertor/githubsnapshotconvertor.go
  utils/formats/snapshotconvertor/githubsnapshotconvertor_test.go
  utils/results/conversion/sarifparser/sarifparser.go
  utils/results/conversion/sarifparser/sarifparser_test.go
  utils/utils.go
Labels: ignore for release

#489 Add Project flag to UploadCdx cmd
  cli/docs/flags.go
  cli/scancommands.go
  commands/upload/uploadcdx.go
  utils/artifactory/artifactoryutils.go
Labels: ignore for release

#522 Show vulnerabilities in Build-Scan SARIF format when project not provided
  cli/scancommands.go
Labels: bug

#523 Update dependencies
  go.mod
  go.sum
Labels: improvement

#528 Added-support-for-Wrapper-using-curation-audit
  cli/docs/flags.go
  cli/scancommands_test.go
Labels: bug

#526 Add ScaResults guard on fail build check when no JAS results
  scans_test.go
  tests/config.go
  tests/consts.go
  utils/results/common.go
Labels: bug

#531 Update SARIF dependency - Fix GH upload when no findings
  go.mod
  go.sum
Labels: bug

#537 Update dependencies for 1.21.1
  go.mod
  go.sum
Labels: ignore for release

#544 Refactor unrelated utils
  commands/audit/audit_test.go
  commands/audit/auditbasicparams.go
  commands/audit/auditnpmparams.go
  commands/audit/auditparams.go
  commands/curation/curationaudit.go
  commands/curation/curationaudit_test.go
  sca/bom/buildinfo/technologies/common_test.go
  sca/bom/buildinfo/technologies/go/golang.go
  utils/golang.go
Labels: ignore for release

#547 Update dependencies
  go.mod
  go.sum
Labels: bug
