Repository jfrog/jfrog-cli-security, pull requests merged in 2025-03, with the labels that each got.

#311 Use new xsc git info struct
  commands/audit/audit_test.go
  commands/git/audit/gitaudit.go
  git_test.go
  go.mod
  go.sum
  utils/scm/gitmanager.go
  utils/scm/gitmanager_test.go
  utils/validations/test_mocks.go
  utils/xsc/analyticsmetrics.go
  utils/xsc/analyticsmetrics_test.go
Labels: ignore for release

#385 Fix flaky tests
  commands/audit/sca/pnpm/pnpm_test.go
  git_test.go
Labels: ignore for release

#381 Move validation dir to tests dir
  audit_test.go
  commands/audit/audit_test.go
  git_test.go
  scans_test.go
  tests/validations/test_mocks.go
  tests/validations/test_validate_sarif.go
  tests/validations/test_validate_sca.go
  tests/validations/test_validate_simple_json.go
  tests/validations/test_validate_summary.go
  tests/validations/test_validation.go
  utils/results/conversion/convertor_test.go
  utils/results/output/securityJobSummary_test.go
  utils/xsc/analyticsmetrics_test.go
  utils/xsc/configprofile_test.go
  xsc_test.go
Labels: ignore for release

#384 Combine multiple runs with same Tool name in SARIF format
  commands/audit/sca/pnpm/pnpm_test.go
  utils/formats/sarifutils/sarifutils.go
  utils/formats/sarifutils/test_sarifutils.go
  utils/results/common.go
  utils/results/conversion/sarifparser/sarifparser.go
Labels: bug

#391 Fix - Conan detection on projects with conanfile.py
  utils/techutils/techutils.go
Labels: bug

#380 Update analyzermanager to v1.15.2
  commands/audit/sca/pnpm/pnpm_test.go
  git_test.go
  jas/analyzermanager.go
Labels: improvement

#396 update dependencies
  go.mod
  go.sum
Labels: ignore for release

#399 Add audit swift & cocoapods flags
  cli/docs/flags.go
Labels: improvement
