Repository jfrog/jfrog-cli-security, pull requests merged in 2025-09, with the labels that each got.

#551 Fix Nuget tests for mac
  .github/actions/install-and-setup/action.yml
Labels: bug

#562 Add FastCI Optimization to GitHub Actions workflow
  .github/workflows/test.yml
Labels: ignore for release

#504 static sca new flow enhancements and fixes
  audit_test.go
  cli/docs/flags.go
  cli/gitcommands.go
  cli/scancommands.go
  cli/utils.go
  commands/audit/audit.go
  commands/git/audit/gitaudit.go
  commands/git/audit/gitauditparams.go
  commands/upload/uploadcdx.go
  commands/upload/uploadcdx_test.go
  jas/analyzermanager.go
  sca/bom/xrayplugin/plugin/config.go
  sca/bom/xrayplugin/plugin/hclogadapter.go
  sca/bom/xrayplugin/plugin/plugin.go
  sca/bom/xrayplugin/xraylibbom.go
  tests/testdata/projects/package-managers/python/pipenv/pipenv-lock/Pipfile
  tests/testdata/projects/package-managers/python/pipenv/pipenv-lock/Pipfile.lock
  tests/validations/test_validation.go
  utils/formats/cdxutils/cyclonedxutils.go
  utils/formats/cdxutils/cyclonedxutils_test.go
  utils/results/common.go
  utils/utils.go
Labels: ignore for release

#541 Add SAST runs to cdx content
  sca/bom/buildinfo/technologies/pnpm/pnpm_test.go
  tests/validations/test_validate_cyclonedx.go
  utils/formats/cdxutils/cyclonedxutils.go
  utils/results/conversion/convertor.go
  utils/results/conversion/cyclonedxparser/cyclonedxparser.go
  utils/results/output/resultwriter.go
  utils/utils.go
Labels: ignore for release, safe to test

#564 Add verbose logs to commands
  go.mod
  go.sum
  sca/bom/buildinfo/technologies/conan/conan.go
  sca/bom/buildinfo/technologies/java/mvn.go
  sca/bom/buildinfo/technologies/pnpm/pnpm.go
  sca/bom/buildinfo/technologies/swift/swiftcommand.go
  utils/results/output/resultwriter.go
Labels: improvement, safe to test

#567 Update Dependencies
  go.mod
  go.sum
Labels: improvement, safe to test
