Repository jfrog/jfrog-cli-security, pull requests merged in 2025-02, with the labels that each got.

#300 Fix Poetry failing test
  commands/audit/sca/python/python_test.go
  tests/testdata/projects/package-managers/python/poetry/my-poetry-project/poetry.lock
  tests/testdata/projects/package-managers/python/poetry/my-poetry-project/pyproject.toml
Labels: ignore for release

#298 Operational risks results duplications in Table format - Bug fix
  utils/results/conversion/simplejsonparser/simplejsonparser.go
Labels: bug

#295 Update to Security-Cli flags descriptions
  cli/docs/flags.go
Labels: ignore for release

#302 Add min version check for gitRepoKey in analytics finalized event
  git_test.go
  utils/utils.go
  utils/xsc/analyticsmetrics.go
  utils/xsc/analyticsmetrics_test.go
Labels: bug

#303 Update dependencies for version release 1.14.2 + test fix
  commands/curation/curationaudit_test.go
  go.mod
  go.sum
Labels: ignore for release

#301 Pass DefaultConfiguration for SARIF output
  utils/formats/sarifutils/sarifutils.go
Labels: bug

#305 Update violations test with ignore rule
  .github/workflows/test.yml
  git_test.go
  tests/config.go
  tests/consts.go
  tests/utils/test_utils.go
Labels: ignore for release

#309 Fix dotnet curation tests after Artifactory CLI migration
  commands/curation/curationaudit_test.go
  go.mod
  go.sum
Labels: ignore for release

#280 Add support for requesting Curation waivers to the CLI
  commands/curation/curationaudit.go
  commands/curation/curationaudit_test.go
Labels: improvement

#316 Update AM version to 1.14.1
  commands/audit/sca/pnpm/pnpm_test.go
  jas/analyzermanager.go
Labels: improvement

#315 Update Dependencies
  go.mod
  go.sum
Labels: ignore for release
